<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <!-- EF Core runtime -->
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.1" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="9.0.1" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="9.0.4" />

    <!-- EF Core Tools (para migrations) -->
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.1">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>

    <!-- Configuração JSON -->
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="9.0.0" />

    <!-- Supabase SDK -->
    <PackageReference Include="Supabase" Version="1.1.1" />

    <!-- Domain -->
    <ProjectReference Include="..\connectWeek.Domain\connectWeek.Domain.csproj" />
  </ItemGroup>

</Project>
