// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using connectWeek.Infra.Data;

#nullable disable

namespace connectWeek.Infra.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("connectWeek.Domain.Entities.Alternativa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Correta")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<string>("PathImagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("QuestaoId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestaoId");

                    b.ToTable("ALTERNATIVA", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Categoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("CATEGORIA", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Conquista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Criterio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("PontosBonus")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("CONQUISTA", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.ConquistaUsuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ConquistaId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ConquistaId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ConquistadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioId1")
                        .HasColumnType("uuid");

                    b.Property<bool>("Visualizado")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("ConquistaId");

                    b.HasIndex("ConquistaId1");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("CONQUISTA_USUARIO", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Desafio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Dificuldade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("EmbaralharQuestoes")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MaxTentativas")
                        .HasColumnType("integer");

                    b.Property<bool>("MostrarResposta")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PathImagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("PercentualMinimo")
                        .HasColumnType("numeric");

                    b.Property<bool>("Publicado")
                        .HasColumnType("boolean");

                    b.Property<int>("QuantidadeQuestoes")
                        .HasColumnType("integer");

                    b.Property<int>("TempoMaximoMin")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("DESAFIO", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.DesafioCategoria", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<Guid>("DesafioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("DesafioId");

                    b.ToTable("DESAFIO_CATEGORIA", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.DesafioQuestao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DesafioId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<Guid>("QuestaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuestaoId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DesafioId");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("QuestaoId1");

                    b.ToTable("DESAFIO_QUESTAO", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Evento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CapacidadeMaxima")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fim")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("InscricaoAberta")
                        .HasColumnType("boolean");

                    b.Property<string>("LinkTransmissao")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Local")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PathImagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("Publicado")
                        .HasColumnType("boolean");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("EVENTO", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.EventoDesafio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DesafioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DesafioId1")
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Liberacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("Obrigatorio")
                        .HasColumnType("boolean");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DesafioId");

                    b.HasIndex("DesafioId1");

                    b.HasIndex("EventoId");

                    b.ToTable("EVENTO_DESAFIO", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.ExecucaoDesafio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Aprovado")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DesafioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("DesafioId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FinalizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("IniciadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Percentual")
                        .HasColumnType("numeric");

                    b.Property<decimal>("Pontuacao")
                        .HasColumnType("numeric");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("TempoGasto")
                        .HasColumnType("integer");

                    b.Property<int>("Tentativa")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UsuarioId1")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DesafioId");

                    b.HasIndex("DesafioId1");

                    b.HasIndex("UsuarioId");

                    b.HasIndex("UsuarioId1");

                    b.ToTable("EXECUCAO_DESAFIO", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Funcao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("Nome")
                        .IsUnique();

                    b.ToTable("FUNCAO", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Questao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CriadoPor")
                        .HasColumnType("uuid");

                    b.Property<string>("Dificuldade")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Enunciado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Explicacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PathImagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("numeric");

                    b.Property<bool>("Publicado")
                        .HasColumnType("boolean");

                    b.Property<string>("TipoQuestao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.Property<int>("VezesUtilizada")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("UsuarioId");

                    b.ToTable("QUESTAO", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.QuestaoCategoria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoriaId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuestaoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CategoriaId");

                    b.HasIndex("QuestaoId");

                    b.ToTable("QUESTAO_CATEGORIA", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.RespostaQuestao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Guid>("AlternativaId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Correta")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ExecucaoId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("Pontuacao")
                        .HasColumnType("numeric");

                    b.Property<Guid>("QuestaoId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("QuestaoId1")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("RespondidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("TempoResposta")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlternativaId");

                    b.HasIndex("ExecucaoId");

                    b.HasIndex("QuestaoId");

                    b.HasIndex("QuestaoId1");

                    b.ToTable("RESPOSTA_QUESTAO", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Ativo")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("EmailVerificado")
                        .HasColumnType("boolean");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PathImagem")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("UltimoAcesso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("USUARIO", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.UsuarioAutenticacao", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AtualizadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CriadoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ProviderSub")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProviderSub")
                        .IsUnique();

                    b.HasIndex("UsuarioId");

                    b.ToTable("USUARIO_AUTENTICACAO", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.UsuarioFuncao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AtribuidoEm")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("AtribuidoPor")
                        .HasColumnType("uuid");

                    b.Property<int>("FuncaoId")
                        .HasColumnType("integer");

                    b.Property<int?>("FuncaoId1")
                        .HasColumnType("integer");

                    b.Property<Guid>("UsuarioId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FuncaoId");

                    b.HasIndex("FuncaoId1");

                    b.HasIndex("UsuarioId");

                    b.ToTable("USUARIO_FUNCAO", (string)null);
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Alternativa", b =>
                {
                    b.HasOne("connectWeek.Domain.Entities.Questao", "Questao")
                        .WithMany("Alternativas")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.ConquistaUsuario", b =>
                {
                    b.HasOne("connectWeek.Domain.Entities.Conquista", "Conquista")
                        .WithMany()
                        .HasForeignKey("ConquistaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("connectWeek.Domain.Entities.Conquista", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("ConquistaId1");

                    b.HasOne("connectWeek.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("connectWeek.Domain.Entities.Usuario", null)
                        .WithMany("Conquistas")
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Conquista");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Desafio", b =>
                {
                    b.HasOne("connectWeek.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.DesafioCategoria", b =>
                {
                    b.HasOne("connectWeek.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Desafios")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("connectWeek.Domain.Entities.Desafio", "Desafio")
                        .WithMany("Categorias")
                        .HasForeignKey("DesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Desafio");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.DesafioQuestao", b =>
                {
                    b.HasOne("connectWeek.Domain.Entities.Desafio", "Desafio")
                        .WithMany("Questoes")
                        .HasForeignKey("DesafioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("connectWeek.Domain.Entities.Questao", "Questao")
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("connectWeek.Domain.Entities.Questao", null)
                        .WithMany("DesafioQuestoes")
                        .HasForeignKey("QuestaoId1");

                    b.Navigation("Desafio");

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Evento", b =>
                {
                    b.HasOne("connectWeek.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.EventoDesafio", b =>
                {
                    b.HasOne("connectWeek.Domain.Entities.Desafio", "Desafio")
                        .WithMany()
                        .HasForeignKey("DesafioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("connectWeek.Domain.Entities.Desafio", null)
                        .WithMany("Eventos")
                        .HasForeignKey("DesafioId1");

                    b.HasOne("connectWeek.Domain.Entities.Evento", "Evento")
                        .WithMany("Desafios")
                        .HasForeignKey("EventoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Desafio");

                    b.Navigation("Evento");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.ExecucaoDesafio", b =>
                {
                    b.HasOne("connectWeek.Domain.Entities.Desafio", "Desafio")
                        .WithMany()
                        .HasForeignKey("DesafioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("connectWeek.Domain.Entities.Desafio", null)
                        .WithMany("Execucoes")
                        .HasForeignKey("DesafioId1");

                    b.HasOne("connectWeek.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("connectWeek.Domain.Entities.Usuario", null)
                        .WithMany("Execucoes")
                        .HasForeignKey("UsuarioId1");

                    b.Navigation("Desafio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Questao", b =>
                {
                    b.HasOne("connectWeek.Domain.Entities.Usuario", "Usuario")
                        .WithMany()
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.QuestaoCategoria", b =>
                {
                    b.HasOne("connectWeek.Domain.Entities.Categoria", "Categoria")
                        .WithMany("Questoes")
                        .HasForeignKey("CategoriaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("connectWeek.Domain.Entities.Questao", "Questao")
                        .WithMany("Categorias")
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categoria");

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.RespostaQuestao", b =>
                {
                    b.HasOne("connectWeek.Domain.Entities.Alternativa", "Alternativa")
                        .WithMany()
                        .HasForeignKey("AlternativaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("connectWeek.Domain.Entities.ExecucaoDesafio", "Execucao")
                        .WithMany("Respostas")
                        .HasForeignKey("ExecucaoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("connectWeek.Domain.Entities.Questao", "Questao")
                        .WithMany()
                        .HasForeignKey("QuestaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("connectWeek.Domain.Entities.Questao", null)
                        .WithMany("Respostas")
                        .HasForeignKey("QuestaoId1");

                    b.Navigation("Alternativa");

                    b.Navigation("Execucao");

                    b.Navigation("Questao");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.UsuarioAutenticacao", b =>
                {
                    b.HasOne("connectWeek.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Autenticacoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.UsuarioFuncao", b =>
                {
                    b.HasOne("connectWeek.Domain.Entities.Funcao", "Funcao")
                        .WithMany()
                        .HasForeignKey("FuncaoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("connectWeek.Domain.Entities.Funcao", null)
                        .WithMany("Usuarios")
                        .HasForeignKey("FuncaoId1");

                    b.HasOne("connectWeek.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Funcoes")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funcao");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Categoria", b =>
                {
                    b.Navigation("Desafios");

                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Conquista", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Desafio", b =>
                {
                    b.Navigation("Categorias");

                    b.Navigation("Eventos");

                    b.Navigation("Execucoes");

                    b.Navigation("Questoes");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Evento", b =>
                {
                    b.Navigation("Desafios");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.ExecucaoDesafio", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Funcao", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Questao", b =>
                {
                    b.Navigation("Alternativas");

                    b.Navigation("Categorias");

                    b.Navigation("DesafioQuestoes");

                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("connectWeek.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Autenticacoes");

                    b.Navigation("Conquistas");

                    b.Navigation("Execucoes");

                    b.Navigation("Funcoes");
                });
#pragma warning restore 612, 618
        }
    }
}
